services:
  frontend:
    container_name: langtest-front
    build:
      context: ./front
      dockerfile: front.dockerfile
    ports:
      - '3000:3000'
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:8080
    depends_on:
      - backend

  backend:
    container_name: langtest-back
    build:
      context: ./Back
      dockerfile: back.dockerfile
    ports:
      - "8080:8080"
    environment:
      DATABASE_URL: ${DATABASE_URL}
    depends_on:
      - db

  db:
    container_name: langtest-db
    image: postgres:17-alpine
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_USER: postgres
      POSTGRES_DB: langtest
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
